# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

domain: ""

lokistack:
  name: lokistack-logging
  namespace: openshift-logging
  port: 8080

prometheus:
  name: thanos-querier
  namespace: openshift-monitoring
  port: 9091

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}